run:
	python run.py

i:
	pip install -r requirements.txt

clean:
	git clean -xdf

ds:
	python run.py dataset

train_c:
	python run.py train -c

train_s:
	python run.py train -s

autotrain_c:
	python run.py autotrain -c

autotrain_s:
	python run.py autotrain -s

test_c:
	python run.py test -c

test_cg:
	python run.py test -cg

test_ce:
	python run.py test -ce

test_ci:
	python run.py test -ci

test_s:
	python run.py test -s

test_sar:
	python run.py test -sar

test_m:
	python run.py test -m

